### ISSUE TITLE
PSRAM not available

### ISSUE THREAD

**Issue by VivantSenior** [justLV/onju-voice#62]
Hi,

I ordered 5 pcbs with already soldered components. Out of these 5 pcbs one reports 0B PSRAM available. I'm using ESPHome with [@tetele's](https://github.com/tetele/) [MicroWakeWord](https://github.com/tetele/onju-voice-satellite/blob/main/esphome/onju-voice-microwakeword.yaml) configuration.

Configuration related to the board itself and PSRAM:
```yaml
esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_ESP32_S3_BOX_BOARD: "y"

psram:
  mode: octal
  speed: 80MHz
````

After upload not much RAM is used:
```
RAM:   [=         ]  11.3% (used 36960 bytes from 327680 bytes)
Flash: [========  ]  82.9% (used 1521433 bytes from 1835008 bytes)
```

But when enabling micro wake word I receive an error:
```
[C][psram:020]: PSRAM:
[C][psram:021]:   Available: NO
...
...
[E][esp-idf:000]: E (20485) AUDIO_PIPELINE: audio_pipeline.c:255 (audio_pipeline_init): Memory exhausted
```

When I enabled debug I can see that there is 0B PSRAM available:
![Bedroom VA PSRAM](https://github.com/user-attachments/assets/fc306241-f21c-4a5c-bc24-5952c5f7367d)

This is the problematic board:
![PCB_no psram](https://github.com/user-attachments/assets/7ccf5f4a-55ed-426e-be1a-83e888cbf7d2)

Other PCB reports much more available PSRAM and even 2 times more free heap:
```
[C][psram:020]: PSRAM:
[C][psram:021]:   Available: YES
[C][psram:024]:   Size: 8191 KB
```
![Kitchen VA PSRAM](https://github.com/user-attachments/assets/a983788e-cfa1-4bb0-82f7-03c1091100c1)
8 291 859 bytes is ~8MB which is accurate for ESP32-S3R8 board.

ESPHome config for both boards is exactly the same. What can be a reason for this issue?
